version: '3.9'
services:
  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/myapp_development

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=ymow
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=myapp_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: